{{- if .Values.IstioGatewayEnabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-gateway-vs
  namespace: {{ $.Values.Namespace }}
spec:
  hosts:
    - {{ .Release.Name }}.dotnet-works.com
  gateways:
    - {{ $.Values.IstioGatewayName }}
  http:
    - route:
        - destination:
            host: "{{ .Release.Name }}-service.{{ $.Values.Namespace }}.svc.cluster.local"
            port:
              number: {{ $.Values.ServicePort }}
  {{- end }}